package org.omg.PortableServer;


/**
* org/omg/PortableServer/THREAD_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u181/11358/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Saturday, July 7, 2018 12:57:16 AM PDT
*/

public interface THREAD_POLICY_ID
{

  /**
  	 * The value representing THREAD_POLICY_ID.
  	 */
  public static final int value = (int)(16L);
}
