package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/ACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u181/11358/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Saturday, July 7, 2018 12:57:16 AM PDT
*/

public interface ACTIVE
{

  /** Object adapter state that indicates normal request processing.
     */
  public static final short value = (short)(1);
}
